### ISSUE TITLE
Magento 2.2.8, email template prints all tracking codes from all orders in the store

### ISSUE THREAD

**Issue by adamraya** [shipperhq/module-shipping-tracker#8] opened 2019-04-29 13:53 UTC
After update to Magento 2.2.8, the email template prints all tracking codes from all orders in the store, not only the tracking codes of the current order.

Seems like now `$_shipment->getAllTracks()` is receiving all tracking codes, is not filtering anymore only the track codes of the current order.
https://github.com/shipperhq/module-shipping-tracker/blob/cf0dab8d3261b5ca5d9ee312cdf4717ef6f5eae1/src/view/frontend/templates/email/shipment/track.phtml#L27

**Comment by ibraheemnabeelfauzi** [comment] 2019-05-03 14:38
Hey @adamraya, 
Thank you for raising this. We're currently looking at and we'll update you with more details soon. 

Cheers.

**Comment by ibraheemnabeelfauzi** [comment] 2019-05-13 21:22
Hey @adamraya  
Would you provide us with more details on what email template are you using? 

Thank you.

**Comment by ibraheemnabeelfauzi** [comment] 2019-05-13 22:30
Hi @adamraya 
Just wanted to follow-up and let you know that we were able to reproduce this issue and it has been escalated to my senior engineers. We'll follow up with more details later on. I currently don't have an ETA on when will the fix be released but we'll keep you posted. 

Cheers.

**Comment by wsajosh** [comment] 2019-05-28 09:54
Hi @adamraya 

Please update to v1.0.3. The issue is resolved in this release

**Closed by wsajosh** 2019-05-28 09:54 UTC
Labels: bug, in progress

**Comment by oviliz** [comment] 2020-11-10 23:16
@wsajosh shouldn't be possible to do `composer update shipperhq/module-shipping-tracker`?
```
$ composer update shipperhq/module-shipping-tracker
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
...
```
It seems that I'm unable to update for some reason.
```
$ composer show  | grep shipperhq
shipperhq/module-shipping-tracker                 1.0.1     Shipping Tracker - By the ShipperHQ Team
```
```
$ cat composer.json | grep shipperhq
        "shipperhq/module-shipping-tracker": "^1.0",
```
Any thoughts?
